apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
stringData:
  # Replace the IP with your MongoDB server's private IP from the terraform output
  MONGO_URI: "mongodb://wizadmin:verysecretpassword123@10.0.1.202:27017/todoDB?authSource=admin"
