apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
stringData:
  # Replace the IP with your MongoDB server's public IP from the terraform output
  MONGO_URI: "mongodb://wizadmin:verysecretpassword123@44.201.130.230:27017/todoDB?authSource=admin"
